// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqfwcjcnrhiwvoufpmjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxZndjamNucmhpd3ZvdWZwbWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1OTgyNTcsImV4cCI6MjA2MDE3NDI1N30.DuqFkv0OlJ2bl9p3t2eu2nUKrABMv35L7EdT3tJh77M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);